---
abstract: 'Alter attribute defaults with less pain'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Moo: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-NewDefaults
provides:
  MooX::NewDefaults:
    file: lib/MooX/NewDefaults.pm
    version: '0.001003'
requires:
  Carp: '0'
  Sub::Exporter::Progressive: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/MooX-NewDefaults/issues
  homepage: https://github.com/kentnl/MooX-NewDefaults
  repository: https://github.com/kentnl/MooX-NewDefaults.git
version: '0.001003'
